site_name: "seismology"
site_description: 'Observational Seismology'
site_author: 'Weiqiang Zhu'
# repo_name: 'seismology'
nav:
    - Overview: README.md
    - Syllabus: syllabus.md
    - Introduction: 00_Introduction.md
    - Obspy:
      - Install packages: obspy/install.md
      - Download catalog: obspy/download_catalog.ipynb
      - Download seismic data: obspy/seismic_waveform.ipynb
      - Realtime data streaming: obspy/animation_seedlink.ipynb
      - Signal processing: obspy/signal_processing.ipynb
    - Earthquake:
      - Earthquake detection: earthquake/detection.ipynb
      - Earthquake location: earthquake/location.ipynb
      - Focal mechanism: earthquake/focal_mechanism.ipynb
      - Phase travel time: earthquake/travel_time.ipynb
      - Earthquake statistics: earthquake/statistics.ipynb
      - Sorting earthquakes: earthquake/sorting.ipynb
    - Visualization: 
      - Projection: visualization/projection.ipynb
theme:
  name: 'material'
plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
